package objetos;

public enum ItemTipo {
    CUARZO, SILICIO, COBRE,
    PLATA, ORO, ACERO, DIAMANTE, MAGNETITA,
    TITANIO, SULFURO, URANIO,
    CABLES, PIEZAS_METAL,
    PIEZA_TANQUE, MODULO_PROFUNDIDAD, PLANO_NAVE
}

